---
title: "Bias examples"
output: html_document
date: "2026-03-31"
---

```{r}
suppressPackageStartupMessages({
  library(epiwraps)
  library(Biostrings)
  library(BSgenome.Hsapiens.UCSC.hg38)
  library(BiocParallel)
  library(patchwork)
  library(ggplot2)
  library(edgeR)
})
```

```{r}
samps <- c(Fixed.37C = "SRX10861478.GSM5290898", Fixed.55C = "SRX10861481.GSM5290901",
           Native.37C = "SRX10861426.GSM5290846", Native.55C = "SRX10861421.GSM5290841")
newNames <- setNames(paste0(names(samps),".",gsub(".+\\.","",samps)), samps)
cols <- setNames(c("#F8766D", "#00BA38", "#619CFF", "#B77FDB"), newNames)
```

```{r, eval=FALSE}
fragInfo <- function(x){
  seqlevelsStyle(x) <- "UCSC"
  x <- keepStandardChromosomes(x, "Homo_sapiens", pruning.mode = "coarse")
  s <- suppressWarnings(getSeq(BSgenome.Hsapiens.UCSC.hg38, x))
  data.frame(width=width(x), gc=letterFrequency(s, letters="GC", as.prob=TRUE)[,1])
}


bp <- MulticoreParam(4, progress=TRUE)
bamfolder <- "/mnt/germain/datasets/CusanovichATACprotocols/aligned/"
d <- dplyr::bind_rows(lapply(samps, \(x){
  dplyr::bind_rows(bamChrChunkApply(paste0(bamfolder, x, ".bam"), FUN=fragInfo, paired=TRUE, BPPARAM = bp))
}), .id="sample")

gc_dens <- dplyr::bind_rows(bplapply(split(d$gc, d$sample),
                                   BPPARAM=bp, function(x){
  res <- density(x)
  data.frame(x = res$x, y = res$y)
}), .id="sample")

wi_dens <- dplyr::bind_rows(bplapply(split(d$width, d$sample),
                                   BPPARAM=bp, function(x){
  res <- density(sqrt(x))
  data.frame(x = res$x^2, y = res$y)
}), .id="sample")

gc_dens$sample <- factor(gc_dens$sample, names(newNames), newNames)
wi_dens$sample <- factor(wi_dens$sample, names(newNames), newNames)
save(gc_dens, wi_dens, file="example_bias.RData")
```

```{r}
load("example_bias.RData")
p1 <- ggplot(gc_dens, aes(x = x, y = y, color=sample)) +
    geom_line(position="identity", linewidth=1) + theme_bw() +
  labs(x="GC content", y="density", title="C: GC bias") +
  scale_color_manual(values=cols)

p2 <- ggplot(wi_dens, aes(x = x, y = y, color=sample)) +
    geom_line(position="identity", linewidth=1) + theme_bw() +
  scale_x_sqrt(limit=c(0,1000), breaks=c(0,100,300,1000)) +
  labs(x="Fragment length", y="density", title="B: Length bias") +
  scale_color_manual(values=cols)
```


```{r}
se <- readRDS("/mnt/germain/datasets/CusanovichATACprotocols/mergedPeaks_SE.rds")
assay(se, "norm") <- edgeR::cpm(calcNormFactors(DGEList(assay(se))))
# se <- se[-59150,]
# se <- betterChromVAR::addGCBias(se, Rsamtools::FaFile("/reference/Homo_sapiens/Ensembl/GRCh38.p10/Sequence/WholeGenomeFasta/Homo_sapiens.GRCh38.dna.toplevel.fa")) 
dd <- rbind(
  data.frame(M=rowMeans(assay(se, "norm")), A=log(assay(se, "norm")[,samps[4]])-log(assay(se, "norm")[,samps[3]]),
             comparison="Native.55C vs Native.37C") )
#dd$GC <- rowData(se)$bias  
p3 <- ggplot(dd, aes(M, A)) + geom_hex(bins=c(70,15)) + scale_x_log10(limits=c(1,1000)) +
    geom_smooth(method="gam") + scale_fill_gradient(low="lightgrey", high="darkred") + 
    labs(x="Mean accessibility", y="Log-foldchange", title="A: Enrichment bias") + 
    facet_wrap(~comparison, nrow=2, scale="free_y") + theme_bw()
```

```{r}
d <- sechm::meltSE(se[,samps], row.names(se), colDat.columns = NA)
d$sample <- factor(newNames[d$sample], newNames)
d$mean <- rowMeans(assay(se,"norm"))
d$ref <- assay(se,"norm")[,samps[["Native.37C"]]]
p3b <- ggplot(d, aes(mean, log((norm+.1)/(ref+.1)), colour=sample, group=sample)) + 
  geom_hline(yintercept=0, linewidth=1, colour="#619CFF") + 
  geom_smooth(method = "gam", alpha = 0.2, color = NA, formula=y~s(x, sp=0.1)) +
  geom_line(stat = "smooth", method = "gam", linewidth = 1, alpha = 1) +
  scale_x_log10(limits=c(1,1000), exp=0) + theme_bw() +
  theme(legend.position="none") + 
  scale_color_manual(values=cols) +
  labs(y="Log-foldchange\nagainst Native.37C", x="Mean accessibility")
```



```{r, fig.width=10, fig.height=5}
p12 <- (p2 + p1 + plot_layout(nrow=1, guides="collect") & 
          guides(color = guide_legend(nrow = 2)) & theme(legend.position = "bottom"))

pdf("example_bias.pdf", width=10, height=5)
cowplot::plot_grid((p3/free(p3b)), p12, rel_widths=c(4,6))
dev.off()
```

```{r, fig.width=10, fig.height=3}
a <- (p3 + theme(legend.position = "none"))
b <- (p2 + xlim(c(20,1000)))
c <- (p1 + xlim(c(0.15,0.9)))
a + b + c + plot_layout(nrow=1, widths=c(4,3,3)) & theme(legend.position = "none")
```

