---
title: "motif interactions"
output: html_document
date: "2026-03-29"
---

```{r}
suppressPackageStartupMessages({
  library(BSgenome.Hsapiens.UCSC.hg38)
  library(betterChromVAR)
  library(motifmatchr)
  library(MotifDb)
  library(universalmotif)
  library(TFBSTools)
  library(limma)
  library(sechm)
  library(ggplot2)
  library(BiocParallel)
  library(epiwraps)
  library(cowplot)
})
```

We get some motifs:

```{r}
motifs <- query(MotifDb, c("HOCOMOCOv13"))
motifs <- motifs[grepl("A$|B$",names(motifs))]
motifs <- do.call(PWMatrixList, convert_motifs(motifs, "TFBSTools-PWMatrix"))
names(motifs) <- sapply(motifs, \(x) x@name)
motifs <- motifs[!duplicated(names(motifs))]
```


# NR3C1

We load the peak counts

```{r}
se <- readRDS("/mnt/germain/plger/DTFAB/fullFrags/NR3C1/runATAC_results/others/countmatrix.rds")
se <- se[rowSums(assay(se))>0,]
assay(se) <- as.matrix(assay(se))
se$group <- gsub("_?[0-9]\\.bam","",colnames(se))
```

Find motif matches:

```{r, eval=FALSE}
moi <- motifmatchr::matchMotifs(motifs, se, genome=BSgenome.Hsapiens.UCSC.hg38)
saveRDS(moi, file="NR3C1_moi.rds")
```

```{r, include=FALSE}
moi <- readRDS("NR3C1_moi.rds")
```


# Screening for modulators of the GCR response

```{r}
discoverMotifInteractions <- function(se, annotation, bait, formula=~group*isInt, coef, minCount=20, ...){
  stopifnot(length(bait)==1 && bait %in% colnames(annotation))
  # for each motif, we create an annotation of which sites contain it _and_ the GCR motif:
  moi2 <- assay(annotation) & assay(annotation)[,bait]
  # we remove combinations too unfrequent for quantification:
  moi2 <- moi2[,colSums(moi2)>=minCount]
  dev <- betterChromVAR(se, moi2)
  # we run a differential analysis, regressing out the overall GCR effects:
  e <- cbind(matrix(assay(dev)[bait,], nrow=nrow(dev)-1, ncol=ncol(dev)),
             assay(dev)[which(row.names(dev)!=bait),])
  cd <- as.data.frame(rbind(colData(se),colData(se)))
  cd$isInt <- rep(c(FALSE,TRUE), each=ncol(dev))
  mm <- model.matrix(formula, data=cd)
  fit <- eBayes(lmFit(e,mm))
  res <- as.data.frame(topTable(fit, coef = coef, number = Inf))
  res$n <- colSums(moi2)[row.names(res)]
  res
}
```


```{r}
res <- discoverMotifInteractions(se, moi, bait="GCR", coef="groupNR3C1:isIntTRUE", minCount=50)
res$motif <- row.names(res)
p1 <- ggplot(res, aes(logFC, -log10(adj.P.Val), label=motif, size=n)) + geom_point(alpha=0.2) + 
  ggrepel::geom_text_repel(data=head(res,15), min.segment.length=0, max.overlaps=30) + 
  scale_size_continuous(transform="sqrt", breaks=c(min(res$n),500,1500)) + theme_bw() + 
  labs(x="Difference in response", size="Number\nof sites", title="Interactions with GCR")
selmo <- head(row.names(res),9)
p2 <- cowplot::plot_grid(plotlist = lapply(motifs[selmo], \(x){
  view_motifs(x, show.positions=FALSE) + theme_void() + theme(legend.position = "none")
  }), ncol=1, labels=selmo, scale=0.95, hjust = 0, label_size = 11, label_fontface = 0)
```

```{r}
#' exploreMotifInteraction
#' 
#' We compare deviations in sites that harbour a single of the two motifs, or
#' the pair of motifs at given distances from each other.
#'
#' @param counts An object inheriting from `RangedSummarizedExperiment`, with
#'   a `bias` column in its `rowData`.
#' @param motifs A named pair of motifs, in a format recognized by 
#'   \code{\link[motifmatchr]{matchMotif}}.
#' @param genome A BSgenome or FaFile object.
#' @param nDistQuantiles The number of distance quantiles between the motif 
#'   matches (up to `maxDist`)
#' @param maxDist The maximum distance between matches.
#' @param ... Any further argument passed to 
#'   \code{\link[betterChromVAR]{betterChromVAR}}.
#'
#' @returns A SummarizedExperiment object of deviations for different types of
#'   interactions between the motifs.
#' 
#' @details
#' Motif pairs are split according to the distance between their centers up to
#' `maxDist` (default 300) into `nDistQuantiles` (default 4) similarly-populated
#' quantiles. Deviations are reported for these different bins, as well as sites
#' harboring only a single motif.
#' @export
#'
#' @examples
exploreMotifInteraction <- function(counts, motifs, genome, nDistQuantiles=4L,
                                    maxDist=300L, ...){
  stopifnot(length(motifs)==2)
  stopifnot(inherits(counts, "RangedSummarizedExperiment"))
  moi <- motifmatchr::matchMotifs(motifs, counts, genome=genome)
  moi2 <- motifCoOccurence(motifs, list(names(motifs)), rowRanges(counts),
                           genome = genome, nDistQuantiles=nDistQuantiles,
                           maxDist=maxDist)
  moi2flat <- Reduce(cbind, moi2)
  colnames(moi2flat) <- paste(colnames(moi2[[1]]),
                              rep(names(moi2), each=ncol(moi2[[1]])), sep=".")
  moiSinglet <- (assay(moi)-rowSums(Reduce("+", moi2))>0)>0
  colnames(moiSinglet) <- paste0(colnames(moiSinglet),"+,",
                                 rev(colnames(moiSinglet)),"-")
  moi <- cbind(assay(moi), moiSinglet, moi2flat)
  colnames(moi) <- gsub("\\.bin","\ndist bin",colnames(moi))
  betterChromVAR(counts, moi, ...)
}
```



```{r, fig.width=12, fig.height=8}
# we pre-compute internal values for speed:
bcvIntern <- betterChromVAR(se, moi, intern=TRUE)
# for each potential partner (here looking at the top 12), we look at the 
# interaction in more detail, and melt the values into a data.frame for plotting
dd <- bplapply(head(row.names(res),9), BPPARAM=MulticoreParam(4, progress=TRUE), \(mo){
  dev <- exploreMotifInteraction(se, motifs[c("GCR", mo)], intern=bcvIntern,
                                 genome=BSgenome.Hsapiens.UCSC.hg38)
  d <- meltSE(dev, row.names(dev))
  d$query <- mo
  d
})
dd <- dplyr::bind_rows(dd)
p3 <- ggplot(dd, aes(feature, deviations)) + geom_hline(yintercept=0, linetype="dashed") + 
  geom_boxplot(aes(fill=group)) + xlab("Site type") + facet_wrap(~query, scale="free", nrow=3) + 
  theme_bw() + theme(axis.text.x=element_text(angle=90, hjust=1, vjust=0.5))
```

```{r, fig.width=10, fig.height=12}
pdf("Figure_motifInteraction.pdf", width=10, height=12)
plot_grid(plot_grid(p1, p2, nrow=1, scale=c(0.95, 0.9), labels="AUTO"),
          p3, nrow=2, scale=c(1,0.95), labels=c(NA, "C"), rel_heights=c(1,2))
dev.off()
```



```{r}
sessionInfo()
```

