---
title: "ATAC dups"
output: html_document
date: "2026-03-30"
---

```{r}
suppressPackageStartupMessages({
  library(rtracklayer)
  library(GenomicRanges)
  library(epiwraps)
  library(BSgenome.Mmusculus.UCSC.mm10)
  library(BiocParallel)
  library(dplyr)
  library(ggplot2)
  library(patchwork)
})
```


```{r, eval=FALSE}
bp <- MulticoreParam(3)

fragInfo <- function(x){
  data.frame(width=width(x), isDup=x$score>1L,
             gc=letterFrequency(getSeq(BSgenome.Mmusculus.UCSC.mm10, x),
                                letters="GC", as.prob=TRUE)[,1])
}

frags <- "/mnt/bohacek/internData/2024_waag_CRS_scMultiome/cellranger/sample_1_trimmed49_imp_rev/outs/atac_fragments.tsv.gz"
a <- tabixChrApply(frags, keepSeqLvls=c("chr1","chr2","chr3"), BPPARAM=bp, fn=fragInfo)
d <- do.call(rbind, a)
d$sample <- "Sample 1"
frags <- "/mnt/bohacek/internData/2024_waag_CRS_scMultiome/cellranger/sample_2_trimmed49_imp_rev/outs/atac_fragments.tsv.gz"
a <- tabixChrApply(frags, keepSeqLvls=c("chr1","chr2","chr3"), BPPARAM=bp, fn=fragInfo)
d2 <- do.call(rbind, a)
d2$sample <- "Sample 2"
d <- rbind(d,d2)
d$sample <- factor(d$sample)
d$width.bin <- cut(d$width, breaks=c(0,60,150,300,Inf))

gc_dens <- dplyr::bind_rows(bplapply(split(d, paste(d$width.bin, d$isDup, d$sample)),
                                   BPPARAM=bp, function(x){
  res <- density(x$gc)
  data.frame(x = res$x, y = res$y, width.bin=x$width.bin[1], sample=x$sample[1], isDup=x$isDup[1])
}))

gc_dens_global <- dplyr::bind_rows(bplapply(split(d, paste(d$isDup, d$sample)),
                                   BPPARAM=bp, function(x){
  res <- density(x$gc)
  data.frame(x = res$x, y = res$y, sample=x$sample[1], isDup=x$isDup[1])
}))


w_dens <- dplyr::bind_rows(bplapply(split(d, paste(d$isDup, d$sample)),
                                   BPPARAM=bp, function(x){
  res <- density(x$width)
  data.frame(x = res$x, y = res$y, sample=x$sample[1], isDup=x$isDup[1])
}))

save(gc_dens, gc_dens_global, w_dens, file="duplicates.RData")
```

```{r}
load("duplicates.RData")
```


```{r}
p1 <- ggplot(gc_dens_global, aes(x = x, y = y, linetype=isDup)) +
    geom_line(position="identity", linewidth=1) + theme_bw() +
  labs(x="GC content", y="density", linetype="Duplicated", tag="A") + 
  facet_wrap(~sample, nrow=2)

p2 <- ggplot(w_dens, aes(x = x, y = y, linetype=isDup)) +
    geom_line(position="identity", linewidth=1) + theme_bw() +
  scale_x_sqrt(limit=c(0,1000), breaks=c(0,100,300,1000)) +
  labs(x="Width", y="density", linetype="Duplicated", tag="B") + 
  facet_wrap(~sample, nrow=2, scale="free_y")

p3 <- ggplot(gc_dens, aes(x = x, y = y, colour=width.bin, linetype=isDup)) +
    geom_line(position="identity", linewidth=1) + theme_bw() +
  labs(x="GC content", y="density", linetype="Duplicated", tag="C",
       color="Fragment\nwidth") + facet_wrap(~sample, nrow=2)
```


```{r, fig.width=10, fig.height=5}
pdf("Figure_ATAC_dups.pdf", width=10, height=5)
p1 + p2 + p3 + plot_layout(guides="collect", widths=c(1,1,2)) & 
  theme(legend.position = "bottom", plot.tag = element_text(face="bold"))
dev.off()
```

