---
title: "Cusanovich dataset"

format:
  html:
    toc: true
    code-fold: true
    code-tools: true
    toc_float: true

author: Jiayi Wang
---

## Dependencies
```{r message=FALSE, warning=FALSE}
suppressPackageStartupMessages({
    library(ggplot2)
   #remotes::install_github("Jiayi-Wang-Joey/WeightInsertModels")
    library(WeightInsertModels)
    library(SummarizedExperiment)
    library(Matrix)
    library(limma)
    library(edgeR)
    library(data.table)
    library(ggrastr)
    library(rtracklayer)
    library(BSgenome.Hsapiens.UCSC.hg38)
})
```

## Spearman's correlation

```{r}
se <- readRDS("/mnt/plger/jwang/Cusanovich/counts_HS.rds")
mtx <- as.matrix(counts(se))
cor_mat <- cor(mtx, method = "spearman", use = "pairwise.complete.obs")
dt <- as.data.table(as.table(cor_mat))
```

```{r}
# setnames(dt, c("sample1", "sample2", "cor"))
# low_samples  <- paste0("GSM529088", 1:6)
# high_samples <- c(paste0("GSM529088", 7:9), paste0("GSM529089", 0:2))
# 
# all_samples <- colnames(cor_mat)
# 
# label_dt <- data.table(
#   sample = all_samples,
#   group = fifelse(
#     all_samples %in% low_samples, "low",
#     fifelse(all_samples %in% high_samples, "high", "other")
#   )
# )
# se2 <- readRDS("/mnt/germain/datasets/CusanovichATACprotocols/mergedPeaks_SE2.rds")
# order <- substr(colnames(se2), 13, 22)
# dt[, sample1 := factor(sample1, levels = order)]
# dt[, sample2 := factor(sample2, levels = order)]
# gg <- ggplot(dt, aes(sample1, sample2, fill = cor)) +
#   geom_tile() +
#   scale_fill_viridis_c(limits = c(0, 1)) +
#   theme_void() +
#   theme(
#     axis.text = element_blank(),
#     axis.title = element_blank(),
#       axis.ticks = element_blank(),
#     legend.key.height = unit(0.4, "cm"),
#     legend.text  = element_text(size = 6),
#     legend.title = element_text(size = 7),
#     plot.margin = margin(t = 20, r = 10, b = 60, l = 60),
#       coord_equal()
#   ) +
#   geom_text(
#     data = label_dt,
#     aes(x = sample, y = 0, label = sample, color = group),
#     angle = 90, hjust = 1, size = 0.8, inherit.aes = FALSE
#   ) +
#   geom_text(
#     data = label_dt,
#     aes(x = 0, y = sample, label = sample, color = group),
#     hjust = 1, size = 0.8, inherit.aes = FALSE
#   ) +
#   scale_color_manual(
#     values = c(
#       "low" = "#1f78b4",    
#       "high" = "#e31a1c",  
#       "other" = "grey"
#     )
#   ) +
#   guides(color = "none") +
#   labs(fill = "Spearman \nCorrelation") +
#   coord_cartesian(clip = "off") +
#   expand_limits(x = 0, y = 2)
# ggsave("plts/cusanovich_heatmap.pdf", gg, height = 15, width = 15, units = "cm")
```



## MA plot

### Origin counts
```{r}
samps <- c(Fixed.37C = "SRX10861478.GSM5290898", Fixed.55C = "SRX10861481.GSM5290901",
           Native.37C = "SRX10861426.GSM5290846", Native.55C = "SRX10861421.GSM5290841")
se <- readRDS("/mnt/germain/datasets/CusanovichATACprotocols/mergedPeaks_SE2.rds")
sra <- read.delim("/mnt/germain/datasets/CusanovichATACprotocols/SraRunTable.txt", sep=",")
md <- fread("https://ftp.ncbi.nlm.nih.gov/geo/series/GSE174nnn/GSE174280/matrix/GSE174280-GPL21697_series_matrix.txt.gz", skip = 39)
md <- setNames(gsub("-Rep[0-9]+","",colnames(md)[-1]), md[1,-1])
sra$name <- md[sra$GEO_Accession..exp.]
md <- as.data.frame(t(sapply(strsplit(sra$name, "-"), \(x) x[c(2,4:6)])))
colnames(md) <- c("Nuclei", "Buffer", "Temperature", "Tn5")
sra <- cbind(sra, md)
row.names(sra) <- paste(sra$Experiment, sra$GEO_Accession..exp., sep=".")
colData(se) <- DataFrame(sra[colnames(se),c("Bases",colnames(md))])

dd <- data.frame(M=rowMeans(assay(se)),
      A=log1p(assay(se)[,samps[4]])-log1p(assay(se)[,samps[3]]), 
      type = "origin")

cd <- colData(se)
pk <- cd[cd$Nuclei=="Native" & cd$Tn5 =="Nextera_Tn5" & cd$Buffer != "Nextera_TD",]
```


### Weighted counts
```{r}
bams <- list.files("/mnt/plger/datasets/CusanovichATACprotocols/aligned", 
    pattern = "\\.bam$",
    full.names = TRUE)
sample <- vapply(bams, \(x) {
    name <- basename(x)
    sub("\\.bam$", "", name)
}, character(1))
names(bams) <- sample
bams <-  bams[rownames(pk)]
atacFrags <- .importFragments(as.list(bams))

peaks <- import.bed(con="/mnt/plger/datasets/CusanovichATACprotocols/peaks/merged.bed")
se2 <- WeightInsertModels::getCounts(atacFrag = atacFrags, ranges = peaks,
                    genome = BSgenome.Hsapiens.UCSC.hg38,
                    species = "Homo sapiens",
                    fragWeight=TRUE, peakWeight=TRUE)

dd2 <- data.frame(M=rowMeans(assay(se2)),
    A=log1p(assay(se2)[,samps[4]])-log1p(assay(se2)[,samps[3]]),
    type = "weights")
    

p2
dd2$type <- "weights"
dd$type <- "origin"
dt <- rbind(dd2, dd)
p2 <- ggplot(dt, aes(M, A)) + geom_hex(bins=c(70,15)) + scale_x_log10(limits=c(1,1000)) +
    geom_smooth(method="gam") + scale_fill_gradient(low="lightgrey", high="darkred") + 
    labs(x="Mean accessibility", y="Log-foldchange", title="Native.55C vs Native.37C") + 
    facet_wrap(~type, nrow=1, scale="free_y") + theme_bw()  

ggsave("plts/cusanovich_MA.pdf", p2, width = 24, height = 7, unit = "cm")
```




